### ISSUE TITLE
hush coin

### ISSUE THREAD

**Issue by Simkas45** [ROZ-MOFUMOFU-ME/zny-nomp#18]
please add supported HUSH.

**Comment by cryptozeny** [comment]
plz more info

**Comment by Simkas45** [comment]
https://github.com/MyHush/hush3

**Comment by cryptozeny** [comment]
could you tell us why zny-nomp supports this coin?

**Comment by Simkas45** [comment]
I think you're going to have to match your pool code to the blocktemplate of the new chain.
Project developer me tell.
Please help me supported hush3 pool, and config json

**Comment by Simkas45** [comment]
[hush3] Cannot run a pool for unsupported algorithm "equihash"

**Comment by ROZ-MOFUMOFU-ME** [comment]
If you need an algorithm called equihash, I need to embed "equihashverify" to zny-nomp, but it is very laborious.
Will you try using z-nomp or s-nomp?
