### ISSUE TITLE
node & npm version

### ISSUE THREAD

**Issue by moyuns-dev** [ROZ-MOFUMOFU-ME/zny-nomp#19]
Hi , you used node & npm what version?   node v7.6.0 is error

**Comment by ROZ-MOFUMOFU-ME** [comment]
Hi,
I am sure it works on node v9 & npm v6
Install node and npm as follows

`sudo apt install nodejs npm`

Install node version control tool "n"
`sudo npm install n -g`

install node v9
`sudo n v9`

Install npm
`sudo npm install npm -g`

Delete old nodejs and npm
`sudo apt purge -y nodejs npm`

Create symbolic link
`sudo ln -sf /usr/local/bin/node /usr/bin/node`
`sudo ln -sf /usr/local/bin/npm /usr/bin/npm`

Check your node & npm version
`node -v`
`npm -v`

Try it

**Comment by cryptozeny** [comment]
good to know! thanks
