### ISSUE TITLE
Daemon does not own pool address

### ISSUE THREAD

**Issue by LoRdMiCk** [ROZ-MOFUMOFU-ME/zny-nomp#20]
the address is owned by the pool wallet... I don't understand why it say it dosent own it.. I tried to erease wallet and close it reopen it change address for the new one but it still didnt work..

2019-12-09 11:33:07 [Payments]  [cpuchain] Daemon does not own pool address - payment processing can not be done with this daemon, {"isvalid":true,"address":"Cxxx9","scriptPubKey":"xxx","isscript":false,"iswitness":false}

**Comment by ROZ-MOFUMOFU-ME** [comment]
Hi
For coins newer than BTC0.17, you may need to add the following to the pool config json file
```
    "BTCover17": true,
    "_comment_BTCover17": "If BTC 0.17 or higher, payment does not work please enable it",
```

And some coins may not work with P2SH addresse, so create a P2PKH address to make it a pool address.
Please try as follows.
`cpuchain-cli getnewaddress" "" legacy "`

Will you try these?

**Comment by LoRdMiCk** [comment]
great thx that works for me :)
