### ISSUE TITLE
No pool configs exists or are enabled in pool_configs folder. No pools spawned.

### ISSUE THREAD

**Issue by bzhubs** [ROZ-MOFUMOFU-ME/zny-nomp#22]
npm start

> zny-nomp@0.0.4 start /data/zny-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2020-01-04 03:57:08 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2020-01-04 03:57:08 [Master]    [PoolSpawner] No pool configs exists or are enabled in pool_configs folder. No pools spawned.
2020-01-04 03:57:08 [Master]    [CLI] CLI listening on port 17117
2020-01-04 03:57:11 [Website]   [Server] Website started on 0.0.0.0:8080

Hello, I have this problem after installation. I don't know how to configure and solve it. Can you help me?

**Comment by bzhubs** [comment]
**cat  /data/zny-nomp/config.json** 
{
    "logLevel": "debug",
    "logColors": true,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": "auto"
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "password": ""
        }
    },

    "website": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8080,
        "stratumHost": "cryppit.com",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 14400,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": true,
            "password": "password10"
        },
        "tlsOptions" : {
            "enabled": false,
            "cert": "",
            "key": ""
        }
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "switching": {
        "switch1": {
            "enabled": false,
            "algorithm": "sha256",
            "ports": {
                "3333": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch2": {
            "enabled": false,
            "algorithm": "scrypt",
            "ports": {
                "4444": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch3": {
            "enabled": false,
            "algorithm": "x11",
            "ports": {
                "5555": {
                    "diff": 0.001,
                    "varDiff": {
                        "minDiff": 0.001,
                        "maxDiff": 1,
                        "targetTime": 15,
                        "retargetTime": 60,
                        "variancePercent": 30
                    }
                }
            }
        }
    },

    "profitSwitch": {
        "enabled": false,
        "updateInterval": 600,
        "depth": 0.90,
        "usePoloniex": true,
        "useCryptsy": true,
        "useMintpal": true,
        "useBittrex": true
    }
}

**cat /data/zny-nomp/coins/sugarchain.json** 
{
    "name": "sugarchain",
    "symbol": "SUGAR",
    "algorithm": "yespower",
    "blockTime": 90,
    "peerMagic": "9feb4b9d",
    "peerMagicTestnet": "b0119070",

    "mainnet": {
      "bech32": "sugar",
      "bip32": {
        "public": "0488b21e"
      },
      "pubKeyHash": "3f",
      "scriptHash": "7d"
    },

    "testnet": {
      "bech32": "tugar",
      "bip32": {
        "public": "043587cf"
      },
      "pubKeyHash": "42",
      "scriptHash": "80"
    }
}

cat  /data/zny-nomp/pool_configs/sugarchain.json 
{
    "enabled": false,
    "coin": "sugarchain.json",

    "address": "",

    "rewardRecipients": {
        "": 1.0
    },

    "paymentProcessing": {
        "minConf": 10,
        "enabled": true,
        "paymentMode": "prop",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 600,
        "minimumPayment": 10,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 34229,
            "user": "username",
            "password": "password"
        }
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "ports": {
        "3032": {
            "diff": 0.5,
            "tls": false,
            "varDiff": {
                "minDiff": 0.00,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 34229,
            "user": "username",
            "password": "password"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 34230,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "",
        "password": "",
        "database": "",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by cryptozeny** [comment]
make the coin config file.

**Comment by cryptozeny** [comment]
check this params again
```json
"stratumHost": "cryppit.com",
"algorithm": "yespower",
"blockTime": 90,
"address": "",
"rewardRecipients": {
    "": 1.0
},
"enabled": false,
```
and refer this
https://github.com/sugarchain-project/doc/blob/master/NOMP.md

**Comment by bzhubs** [comment]
Thank you! I'll try.

**Comment by cryptozeny** [comment]
BTW, `"blockTime": 90,` @ROZ-MOFUMOFU-ME what do you think?

**Comment by ROZ-MOFUMOFU-ME** [comment]
I will fix it to the correct block time, thank you

**Comment by ROZ-MOFUMOFU-ME** [comment]
https://github.com/ROZ-MOFUMOFU-ME/zny-nomp/commit/38cd562cb03cc3cf0dbf677d73f53ee5d391a0bd

**Comment by bzhubs** [comment]
https://github.com/sugarchain-project/doc/blob/master/NOMP.md

Still not how to configure

**Comment by ROZ-MOFUMOFU-ME** [comment]
Set up and enable this file
https://github.com/ROZ-MOFUMOFU-ME/zny-nomp/blob/master/pool_configs/sugarchain_example.json


> https://github.com/sugarchain-project/doc/blob/master/NOMP.md
> 
> Still not how to configure

**Comment by bzhubs** [comment]
> BTW, `"blockTime": 90,` @ROZ-MOFUMOFU-ME what do you think?



> Set up and enable this file
> https://github.com/ROZ-MOFUMOFU-ME/zny-nomp/blob/master/pool_configs/sugarchain_example.json
> 
> > https://github.com/sugarchain-project/doc/blob/master/NOMP.md
> > Still not how to configure

cat /data/zny-nomp/pool_configs/sugarchain.json
{
    "name": "sugarchain",
    "symbol": "SUGAR",
    "algorithm": "YespowerSugar",
    "peerMagic": "9feb4b9d",
    "peerMagicTestnet": "b0119070",

    "mainnet": {
      "bech32": "sugar",
      "bip32": {
        "public": "0488b21e"
      },
      "pubKeyHash": "3f",
      "scriptHash": "7d"
    },

    "testnet": {
      "bech32": "tugar",
      "bip32": {
        "public": "043587cf"
      },
      "pubKeyHash": "42",
      "scriptHash": "80"
    }
}

Is that so, please?

**Comment by ROZ-MOFUMOFU-ME** [comment]
It is the contents of the coin configuration file, you do not need to touch it.
sugarchain_example.json is a sample pool configuration file that you need to set up.

**Comment by bzhubs** [comment]
> It is the contents of the coin configuration file, you do not need to touch it.
> sugarchain_example.json is a sample pool configuration file that you need to set up.

Do I just need to configure coins/sugarcain.json?

**Comment by ROZ-MOFUMOFU-ME** [comment]
You do not need to touch it.
All you need to set up is pool_configs/sugarchain.json
Please refer to the sample file.

**Comment by bzhubs** [comment]
> You do not need to touch it.
> All you need to set up is pool_configs/sugarchain.json
> Please refer to the sample file.

Ok, Thank you very much! I will try.

**Comment by ROZ-MOFUMOFU-ME** [comment]
"enabled": true,

Do not forget this

**Comment by bzhubs** [comment]
> "enabled": true,
> 
> Do not forget this

Ok, thank you.
