### ISSUE TITLE
yespowerIOTS unknow algo

### ISSUE THREAD

**Issue by carlosfusion** [ROZ-MOFUMOFU-ME/zny-nomp#23]
Hello when i try to add iots coin its say yespowerIOTS, how can i add the algo? any help thank you

**Comment by cryptozeny** [comment]
hey there, this is not helpdesk...

**Comment by ROZ-MOFUMOFU-ME** [comment]
When I added a coin for the YesPoWer algorithm, I made changes to the following 3 repositories

https://github.com/ROZ-MOFUMOFU-ME/node-multi-hashing-yescrypt-0.5/commit/2fa9bab1b05f1e49672ba419b29f8e9c24f84d5c

https://github.com/ROZ-MOFUMOFU-ME/node-stratum-pool-yescrypt-0.5/commit/0acbd0c4b6eed2f4439f11f01534de95c21d5f2e

https://github.com/ROZ-MOFUMOFU-ME/zny-nomp/commit/c6288b57bb4962a330aed83c83da99435862d2bb
