### ISSUE TITLE
Payments error

### ISSUE THREAD

**Issue by swa74** [ROZ-MOFUMOFU-ME/zny-nomp#24]
I started the swamp pool, it finds the blocks, but there are no payments.

 [swamp] Error sending payments, decreased rewards by too much!!!

    "paymentProcessing": {
	"minConf": 10,
        "enabled": true,
        "paymentMode": "prop",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 600,
        "minimumPayment": 0.01,
        "maxBlocksPerPayment": 5,
        "daemon": {
            "host": "127.0.0.1",
            "port": 33335,
            "user": "login",
            "password": "pass"

 Immature: 47.52178643 Bal: 0
 Paid: 0

What does he not like?

**Comment by ROZ-MOFUMOFU-ME** [comment]
I don't know much about that coin, but it looks like you needs to be set up correctly.
https://github.com/z-classic/z-nomp/blob/104dcf33f649090c2dd6acda6b4aa37ea68c8f55/libs/paymentProcessor.js#L1186
