### ISSUE TITLE
Ask you a question, how to add founder rewards to the mining pool,

### ISSUE THREAD

**Issue by wahaobi** [ROZ-MOFUMOFU-ME/zny-nomp#25]
请教你一个问题，矿池怎么添加创始人奖励，Ask you a question, how to add founder rewards to the mining pool,

debug.log
AcceptBlock: CTransaction::CheckTransaction() : founders reward missing, Founders' reward check failed (code 69)

**Comment by ROZ-MOFUMOFU-ME** [comment]
Hi,
For example, Zcash seems to be set like this
https://github.com/z-classic/z-nomp/blob/master/coins/zcash.json
