### ISSUE TITLE
Hi, ask you a question, how to solve this payment problem.

### ISSUE THREAD

**Issue by joey-crypto** [ROZ-MOFUMOFU-ME/zny-nomp#26]
when i set coin based on BTCOVER17 as this:    
"BTCover17": true,
    "_comment_BTCover17": "If BTC 0.17 or higher, payment does not work please enable it",
it shows this error:

__**The address provided is not from the daemon wallet - this is required for POS coins.**__

**Comment by ROZ-MOFUMOFU-ME** [comment]
Which coin is it?
Some coins require detailed setting changes.
You can send me a pull request!
