### ISSUE TITLE
It's not available for node v12+

### ISSUE THREAD

**Issue by peipeiTu** [ROZ-MOFUMOFU-ME/zny-nomp#30]
Error when npm install the package node-multi-hashing-yescrypt-0.5.
Is there any update plan for supporting node v12+?

**Comment by ROZ-MOFUMOFU-ME** [comment]
I haven't planned it.
I will consider if the original nomp and z-nomp correspond.

**Comment by ROZ-MOFUMOFU-ME** [comment]
Hi,
I made ZNY-NOMP compatible with node v12.
I think it will work!

https://github.com/ROZ-MOFUMOFU-ME/node-multi-hashing/blob/8171443b1fdb9396a7852901a0cd7b2df80a752b/multihashing.cc

**Comment by peipeiTu** [comment]
Thanks a lot! I will try it soon!
