### ISSUE TITLE
通貨名にスペースを含むとstatsページが正しく動作しない

### ISSUE THREAD

**Issue by zinntikumugai** [ROZ-MOFUMOFU-ME/zny-nomp#4]
![image](https://user-images.githubusercontent.com/16275962/45535084-357f1380-b838-11e8-8720-7f7389a95a80.png)
javascriptの自動更新がおそらくタイトルの通りで動作していません
気力で
```js
for (var pool in stats.pools) {
var poolname = pool;
console.log(pool, poolname);
poolname = poolname.split(' ').join('_');
```
のようなコードを入れてみました所グラフが描画されるようになりましたがその他は変わりませんでした(また正常に動作してるようには見えませんでした)
![image](https://user-images.githubusercontent.com/16275962/45535259-d968bf00-b838-11e8-9e9a-cbaf0545c0bd.png)

**Comment by ROZ-MOFUMOFU-ME** [comment]
NOMP系はスペースを含む通貨名の取り扱いを想定していないようですね。
見たところ大がかりな修正が必要になりそうです。

**Comment by zinntikumugai** [comment]
configを直したほうが低コストか...
