### ISSUE TITLE
add algo

### ISSUE THREAD

**Issue by vrfebet** [ROZ-MOFUMOFU-ME/zny-nomp#5]
Hello,
how can i add algo yescryptR16?
I made:
zny-nomp/coins/elicoin.json

{
    "name": "Elicoin",
    "symbol": "ELI",
    "algorithm": "yescryptR16"
}

zny-nomp/pool_configs/elicoin.jso

{
    "enabled": true,
    "coin": "elicoin.json",
    "address": "EVSixLxC6p59tQGqnr4PNXnqAPxxxxxx",
    "rewardRecipients": {
        "ERCaoE9AcDMcraXCHXc1o1Ybazxxxxxx": 0
    },
    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 60,
        "minimumPayment": 0.01,
        "daemon": {
            "host": "127.0.0.1",
            "port": 9999,
            "user": "me-user",
            "password": "my-pw"
        }
    },
    "ports": {
        "63348": {
            "diff": 0.05,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 2,
                "targetTime": 50,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
        "63349": {
            "diff": 1
        }
    },
    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 9999,
            "user": "me-user",
            "password": "my-pw"
        }
    ],
    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 5889,
        "disableTransactions": true
    },
    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "vtc",
        "checkPassword": true,
        "autoCreateWorker": false
    },
    "mongoMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "user": "",
        "pass": "",
        "database": "vtc",
        "authMechanism": "DEFAULT"
    }
}

but if i run:
in /my-patch/zny-nomp/
 npm start
then:
2018-09-14 14:54:57 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not rai                            sed
2018-09-14 14:54:57 [Master]    [elicoin] Cannot run a pool for unsupported algorithm "yescryptR16"
2018-09-14 14:54:57 [Master]    [PoolSpawner] No pool configs exists or are enabled in pool_configs folder. No pools spawned.
2018-09-14 14:54:57 [Master]    [CLI] CLI listening on port 17117
2018-09-14 14:54:58 [Website]   [Server] Website started on 192.168.2.102:8088

can somebody help me?

Is there anything else you need?
Is it even possible?

Thanks

**Comment by ROZ-MOFUMOFU-ME** [comment]
I added Elicoin. However, verification is inadequate.

**Comment by vrfebet** [comment]
cool, I'll try

**Comment by vrfebet** [comment]
where can I check why the paymentProcessing is not working? connect worker and mining is fine. Mining coin is in daemon wallet, but not redistribute to miners....
I do not know the diagnostic procedures to look for an error.
thank you for your help

**Comment by vrfebet** [comment]
tested here:
http://84.242.74.251:8585

**Comment by ROZ-MOFUMOFU-ME** [comment]
Please search all NOMP error messages.
There should be some hints.

**Comment by vrfebet** [comment]
thank 
just that I can not find any error anywhere.
the log is all green:
http://febet.cz/payments-eli.png
I also checked everything in /var/log and I can not find any error anywhere
I do not know what to look for now....

**Comment by vrfebet** [comment]
for payment there is always only this one line (see img)

**Comment by ROZ-MOFUMOFU-ME** [comment]
hi,
I did the investigation, but I did not understand the cause.
Elicoin was probably cloned from Yenten.
My source code is ported from the following yenten-pool repository.
https://github.com/ohashi3d/y-nomp
Why do not you ask him?
Thank you for your patience.

**Comment by vrfebet** [comment]
thank you
