### ISSUE TITLE
low diff error

### ISSUE THREAD

**Issue by yushufang** [ROZ-MOFUMOFU-ME/zny-nomp#8]
hi there, I set up a monacoin pool, but it keep showing low diff error, do you have any idea? thanks 

_> 2019-04-04 15:12:19 [Switching]	[Setup] (lyra2re2) Setting proxy difficulties after pool start
> 2019-04-04 15:12:31 [Pool]	[monacoin] (Thread 1) Block notification via RPC polling
> 2019-04-04 15:12:35 [Pool]	[monacoin] (Thread 1) Unauthorized  pSnRHMiCrDn78FNQLqLrVswe7mGY7xaNtN:x [::ffff:117.144.202.146]
> 2019-04-04 15:13:18 [Pool]	[monacoin] (Thread 1) Authorized PScca73iZe43H5Nz9j8FFWNPex5LJADED8:x [::ffff:117.144.202.146]
> 2019-04-04 15:13:25 [Pool]	[monacoin] (Thread 1) Share rejected: {"job":"2","ip":"::ffff:117.144.202.146","worker":"PScca73iZe43H5Nz9j8FFWNPex5LJADED8","difficulty":0.5,"error":"low difficulty share of 0.0000032848568802520194"}
> 2019-04-04 15:13:26 [Pool]	[monacoin] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
> 2019-04-04 15:13:27 [Pool]	[monacoin] (Thread 1) Share rejected: {"job":"3","ip":"::ffff:117.144.202.146","worker":"PScca73iZe43H5Nz9j8FFWNPex5LJADED8","difficulty":0.5,"error":"low difficulty share of 7.497820220025431e-8"}
> 2019-04-04 15:13:27 [Pool]	[monacoin] (Thread 1) Share rejected: {"job":"3","ip":"::ffff:117.144.202.146","worker":"PScca73iZe43H5Nz9j8FFWNPex5LJADED8","difficulty":0.5,"error":"low difficulty share of 9.366878023093629e-8"}_

**Comment by ROZ-MOFUMOFU-ME** [comment]
I could not confirm any abnormality in my environment.
Does the same error occur with another miner software?
